### ISSUE TITLE
I suggest K-Means Clustering or Hierarchical Clustering could also be the greatest algorithm for solving this problem.

### ISSUE THREAD

**Issue by Shritesh99** [feat7/symptom-to-disease-prediction#1]

**Comment by feat7** [comment]
This project is just a pet project for others to use.
Random Forest Classifier gives Accuracy 100%. Infact even Descision Trees will give 100% accuracy for the data is preprocessed so good.

I don't have intentions to manage this project. If you want to, feel free to make a PR. 
I might change my thoughts if I see something interesting in here. 😁
